sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    tiles.placeOnRandomTile(sprite, sprites.castle.tilePath5)
})
let currentEnemyDistance = 0
tiles.setCurrentTilemap(tilemap`level2`)
let hero = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . . e e 4 1 f d d f 1 4 e e . . 
    . . f e e d d d d d d e e f . . 
    . . . f e e 4 4 4 4 e e f . . . 
    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
    . . . . . f f f f f f . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(hero)
let enemyMaxSpeed = 80
tiles.placeOnRandomTile(hero, sprites.castle.tilePath5)
let hunter = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdfff......
    .....f111cbfbfc111f.....
    .....fb1b1ffff1b1bf.....
    .....ffbffffffffbff.....
    .........ffffff.........
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
tiles.placeOnRandomTile(hunter, sprites.castle.tilePath5)
scene.cameraFollowSprite(hero)
pathfinding.start_enemies_following_player_with_speed(hero, enemyMaxSpeed)
